/**
 * Database Error Codes mapped to HTTP Status Codes
 * Supports both PostgreSQL and MySQL
 */

// PostgreSQL Error Codes
export const POSTGRES_ERROR_CODES = {
  UNIQUE_VIOLATION: '23505',
  FOREIGN_KEY_VIOLATION: '23503',
  NOT_NULL_VIOLATION: '23502',
  CHECK_VIOLATION: '23514',
  SERIALIZATION_FAILURE: '40001',
  DEADLOCK_DETECTED: '40P01',
  INVALID_TEXT_REPRESENTATION: '22P02',
  SYNTAX_ERROR: '42601',
  UNDEFINED_TABLE: '42P01',
  UNDEFINED_COLUMN: '42703',
} as const;

// MySQL Error Codes
export const MYSQL_ERROR_CODES = {
  DUPLICATE_ENTRY: 1062,
  FOREIGN_KEY_CONSTRAINT: 1452,
  NULL_CONSTRAINT: 1048,
  DEADLOCK: 1213,
  LOCK_WAIT_TIMEOUT: 1205,
  DATA_TOO_LONG: 1406,
  INVALID_DATETIME: 1292,
} as const;

// HTTP Status Code Mappings
export const DB_ERROR_HTTP_STATUS = {
  CONFLICT: 409,
  BAD_REQUEST: 400,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_SERVER_ERROR: 500,
} as const;

/**
 * Error code to HTTP status mapping
 */
export const ERROR_CODE_MAPPING = new Map<string | number, number>([
  // PostgreSQL
  [POSTGRES_ERROR_CODES.UNIQUE_VIOLATION, DB_ERROR_HTTP_STATUS.CONFLICT],
  [POSTGRES_ERROR_CODES.FOREIGN_KEY_VIOLATION, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
  [POSTGRES_ERROR_CODES.NOT_NULL_VIOLATION, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
  [POSTGRES_ERROR_CODES.CHECK_VIOLATION, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
  [POSTGRES_ERROR_CODES.SERIALIZATION_FAILURE, DB_ERROR_HTTP_STATUS.SERVICE_UNAVAILABLE],
  [POSTGRES_ERROR_CODES.DEADLOCK_DETECTED, DB_ERROR_HTTP_STATUS.SERVICE_UNAVAILABLE],
  [POSTGRES_ERROR_CODES.INVALID_TEXT_REPRESENTATION, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
  [POSTGRES_ERROR_CODES.SYNTAX_ERROR, DB_ERROR_HTTP_STATUS.INTERNAL_SERVER_ERROR],
  [POSTGRES_ERROR_CODES.UNDEFINED_TABLE, DB_ERROR_HTTP_STATUS.INTERNAL_SERVER_ERROR],
  [POSTGRES_ERROR_CODES.UNDEFINED_COLUMN, DB_ERROR_HTTP_STATUS.INTERNAL_SERVER_ERROR],
  
  // MySQL
  [MYSQL_ERROR_CODES.DUPLICATE_ENTRY, DB_ERROR_HTTP_STATUS.CONFLICT],
  [MYSQL_ERROR_CODES.FOREIGN_KEY_CONSTRAINT, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
  [MYSQL_ERROR_CODES.NULL_CONSTRAINT, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
  [MYSQL_ERROR_CODES.DEADLOCK, DB_ERROR_HTTP_STATUS.SERVICE_UNAVAILABLE],
  [MYSQL_ERROR_CODES.LOCK_WAIT_TIMEOUT, DB_ERROR_HTTP_STATUS.SERVICE_UNAVAILABLE],
  [MYSQL_ERROR_CODES.DATA_TOO_LONG, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
  [MYSQL_ERROR_CODES.INVALID_DATETIME, DB_ERROR_HTTP_STATUS.BAD_REQUEST],
]);

/**
 * User-friendly error messages for common database errors
 */
export const DB_ERROR_MESSAGES = {
  UNIQUE_VIOLATION: 'A record with this value already exists',
  FOREIGN_KEY_VIOLATION: 'Referenced record does not exist',
  NOT_NULL_VIOLATION: 'Required field cannot be empty',
  CHECK_VIOLATION: 'Invalid value provided',
  SERIALIZATION_FAILURE: 'Database operation failed due to concurrent modification. Please try again',
  DEADLOCK_DETECTED: 'Database operation failed due to deadlock. Please try again',
  INVALID_TEXT_REPRESENTATION: 'Invalid data format provided',
  DEFAULT: 'A database error occurred',
} as const;
